spring.application.name=factura-auditoria-core
logging.config=classpath:log-config.xml
jwt.secret=igY9YK0WBFWxhkKViLLqaDW7pCAVRUmr

spring.datasource.primary.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.primary.jndi-name=smtJndi
spring.datasource.secondary.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.secondary.jndi-name=tiendasJndi

mail.smtp.host=10.2.3.16
mail.from=auditoria@facturacion.com